[package]
name = "fantasy"
version = "0.1.0"
authors = ["Shaunak Kishore <kshaunak@gmail.com>"]

[dependencies]
rand = "0.6"
regex = "1"
rustc-hash = "1.0.1"

[profile.release]
debug = true

[lib]
path = "src/exports.rs"
crate-type = ["cdylib"]
