[package]
name = "fantasy"
version = "0.1.0"
authors = ["Shaunak Kishore <kshaunak@gmail.com>"]

[dependencies]
jemallocator = "0.1.9"
regex = "1"
rustc-hash = "1.0.1"

[profile.release]
debug = true
