type Map<T> = {[index: string]: T};

const NUKTAS: Map<string> = {
  'क': 'क़',
  'ख': 'ख़',
  'ग': 'ग़',
  'ज': 'ज़',
  'ड': 'ड़',
  'ढ': 'ढ़',
  'फ': 'फ़',
};

const SYMBOLS = {
  anusvara: 'ं',
  chandrabindu: 'ँ',
  nukta: '़',
  om: 'ॐ',
  virama: '\u094D',
  visarga: '\u0903',
};

const TRANSLITERATIONS: Map<string[]> = {
  // Vowels.
  'अ': ['a'],
  'आ': ['aa', 'a'],
  'इ': ['i'],
  'ई': ['ee', 'i'],
  'उ': ['u'],
  'ऊ': ['oo', 'u'],
  'ऋ': ['ri'],
  'ऌ': ['li'],
  'ऍ': ['e'],
  'ए': ['e'],
  'ऐ': ['ai'],
  'ऑ': ['o'],
  'ओ': ['o'],
  'औ': ['au'],
  'ॠ': ['ru'],
  'ॡ': ['lu'],
  // Consonants.
  'क': ['k'],
  'ख': ['kh'],
  'ग': ['g'],
  'घ': ['gh'],
  'ङ': ['n'],
  'च': ['ch', 'c'],
  'छ': ['ch', 'chh'],
  'ज': ['j'],
  'झ': ['jh'],
  'ञ': ['n'],
  'ट': ['t'],
  'ठ': ['th'],
  'ड': ['d'],
  'ढ': ['dh'],
  'ण': ['n'],
  'त': ['t', 'th'],
  'थ': ['th'],
  'द': ['d', 'dh'],
  'ध': ['dh'],
  'न': ['n'],
  'प': ['p'],
  'फ': ['ph', 'f'],
  'ब': ['b'],
  'भ': ['bh'],
  'म': ['m'],
  'य': ['y'],
  'र': ['r'],
  'ल': ['l'],
  'व': ['v', 'w'],
  'श': ['sh'],
  'ष': ['sh'],
  'स': ['s'],
  'ह': ['h'],
  'ळ': ['l'],
  'ऴ': ['l'],
  'क़': ['k'],
  'ख़': ['kh'],
  'ग़': ['g'],
  'ज़': ['z'],
  'ड़': ['r', 'd'],
  'ढ़': ['rh', 'dh'],
  'ऩ': ['n'],
  'फ़': ['f'],
  'य़': ['y'],
  'ऱ': ['r'],
  // Structural symbols from syllabization.
  a: ['a', ''],
  n: ['n', 'm', ''],
  y: ['y', ''],
};

const VOWELS: Map<string> = {
  'अ': '',
  'आ': '\u093E',
  'इ': '\u093F',
  'ई': '\u0940',
  'उ': '\u0941',
  'ऊ': '\u0942',
  'ऋ': '\u0943',
  'ऌ': '\u0962',
  'ऍ': '\u0946',
  'ए': '\u0947',
  'ऐ': '\u0948',
  'ऑ': '\u094A',
  'ओ': '\u094B',
  'औ': '\u094C',
  'ॠ': '\u0944',
  'ॡ': '\u0963',
};

const VOWEL_SIGNS: Map<string> = {};
Object.keys(VOWELS).forEach((x) => VOWEL_SIGNS[VOWELS[x]] = x);

export {NUKTAS, SYMBOLS, TRANSLITERATIONS, VOWELS, VOWEL_SIGNS};
