type Map<T> = {[index: string]: T};

const NUKTAS: Map<string> = {
  'क': 'क़',
  'ख': 'ख़',
  'ग': 'ग़',
  'ज': 'ज़',
  'ड': 'ड़',
  'ढ': 'ढ़',
  'फ': 'फ़',
};

const SYMBOLS = {
  anusvara: 'ं',
  chandrabindu: 'ँ',
  nukta: '़',
  om: 'ॐ',
  virama: '\u094D',
  visarga: '\u0903',
};

const TRANSLITERATIONS: Map<string[]> = {
  // Vowels.
  'अ': ['a', 'e', 'i', 'o', 'u', 'aa'],
  'आ': ['aa', 'a'],
  'इ': ['a', 'e', 'i', 'o', 'u', 'ee'],
  'ई': ['ee', 'i'],
  'उ': ['a', 'e', 'i', 'o', 'u', 'oo'],
  'ऊ': ['oo', 'u'],
  'ऋ': ['ri'],
  'ऌ': ['li'],
  'ऍ': ['e'],
  'ए': ['a', 'e', 'i', 'o', 'u', 'ai'],
  'ऐ': ['ai', 'e', 'a'],
  'ऑ': ['o'],
  'ओ': ['a', 'e', 'i', 'o', 'u', 'au'],
  'औ': ['au', 'aw', 'ou', 'ow', 'o'],
  'ॠ': ['ru'],
  'ॡ': ['lu'],
  // Consonants.
  'क': ['k', 'kh'],
  'ख': ['kh', 'k'],
  'ग': ['g', 'gh'],
  'घ': ['gh', 'g'],
  'ङ': ['n'],
  'च': ['ch', 'c'],
  'छ': ['ch', 'chh'],
  'ज': ['j', 'jh', 'z'],
  'झ': ['jh', 'j'],
  'ञ': ['n'],
  'ट': ['t', 'th'],
  'ठ': ['th', 't'],
  'ड': ['d', 'dh'],
  'ढ': ['dh', 'd'],
  'ण': ['n'],
  'त': ['t', 'th'],
  'थ': ['th', 't'],
  'द': ['d', 'dh'],
  'ध': ['dh', 'd'],
  'न': ['n'],
  'प': ['p', 'ph'],
  'फ': ['ph', 'f', 'p'],
  'ब': ['b', 'bh'],
  'भ': ['bh', 'b'],
  'म': ['m'],
  'य': ['y'],
  'र': ['r'],
  'ल': ['l'],
  'व': ['v', 'w'],
  'श': ['sh', 's'],
  'ष': ['sh', 's'],
  'स': ['s', 'sh'],
  'ह': ['h'],
  'ळ': ['l'],
  'ऴ': ['l'],
  'क़': ['k', 'kh'],
  'ख़': ['kh', 'k'],
  'ग़': ['g', 'gh'],
  'ज़': ['z', 'j'],
  'ड़': ['r', 'd'],
  'ढ़': ['rh', 'dh', 'r', 'd'],
  'ऩ': ['n'],
  'फ़': ['f', 'ph', 'p'],
  'य़': ['y'],
  'ऱ': ['r'],
  // Structural symbols from syllabization.
  a: ['a', 'e', 'i', 'o', 'u', ''],
  e: ['h', 'n', 'in', 'ih', ''],
  n: ['n', 'm', ''],
  x: ['n', 'm', 'in', 'ih', ''],
  y: ['y', ''],
  z: ['a', 'e', 'i', 'o', 'u', ''],
};

const VOWELS: Map<string> = {
  'अ': '',
  'आ': '\u093E',
  'इ': '\u093F',
  'ई': '\u0940',
  'उ': '\u0941',
  'ऊ': '\u0942',
  'ऋ': '\u0943',
  'ऌ': '\u0962',
  'ऍ': '\u0946',
  'ए': '\u0947',
  'ऐ': '\u0948',
  'ऑ': '\u094A',
  'ओ': '\u094B',
  'औ': '\u094C',
  'ॠ': '\u0944',
  'ॡ': '\u0963',
};

const VOWEL_SIGNS: Map<string> = {};
Object.keys(VOWELS).forEach((x) => VOWEL_SIGNS[VOWELS[x]] = x);

export {NUKTAS, SYMBOLS, TRANSLITERATIONS, VOWELS, VOWEL_SIGNS};
